### PR TITLE
CK-710 Rebasing latest changes

### PR DESCRIPTION
**Pull request by cwshevlin**
This PR says it's like 11 commits behind, but I've rebased so I don't know what's going on with that. This PR has all of my custom changes along with the updates from Google. I think the only way to test this is to merge it in, because I'm not sure we can point our podspec to this branch. I'll keep investigating that.

### CODE REVIEW

**Comment by timoman** [comment]
well, I say :shipit: since it'll be more effort to try to test on a separate branch than to just go live and revert if needed (also since this isn't currently user-facing)

**Comment by cwshevlin** [comment]
@timoman Currently trying pod install with Google's latest, if that works we should be good, because this is just changes to the xib.

**Comment by cwshevlin** [comment]
@timoman Blocked by a problem in APAsync that I don't understand. I'm hopping off this for now and will pick it up after I do some web work.

**Comment by cwshevlin** [comment]
Closing in favor of Tim's PR.

**Pull request closed without merging**
